Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure(figsize=(20,20))
_ = tree.plot_tree(clf, feature_names=list(df.columns.values)[:4], class_names=list(df.columns.values)[4] ,filled=True)
------------------

[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-4-d08fb1e8fe37>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mfig[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m20[0m[0;34m,[0m[0;36m20[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0m_[0m [0;34m=[0m [0mtree[0m[0;34m.[0m[0mplot_tree[0m[0;34m([0m[0mclf[0m[0;34m,[0m [0mfeature_names[0m[0;34m=[0m[0mlist[0m[0;34m([0m[0mdf[0m[0;34m.[0m[0mcolumns[0m[0;34m.[0m[0mvalues[0m[0;34m)[0m[0;34m[[0m[0;34m:[0m[0;36m4[0m[0;34m][0m[0;34m,[0m [0mclass_names[0m[0;34m=[0m[0mlist[0m[0;34m([0m[0mdf[0m[0;34m.[0m[0mcolumns[0m[0;34m.[0m[0mvalues[0m[0;34m)[0m[0;34m[[0m[0;36m4[0m[0;34m][0m [0;34m,[0m[0mfilled[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'clf' is not defined
NameError: name 'clf' is not defined

